// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'StudentsList.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6162094308580178647),
      name: 'Students',
      lastPropertyId: const IdUid(5, 5873433206237132622),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5219891037081140423),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4062069599606153745),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2523391093420303965),
            name: 'edad',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8148964876142222706),
            name: 'hobbie',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5873433206237132622),
            name: 'nacimiento',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6162094308580178647),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Students: EntityDefinition<Students>(
        model: _entities[0],
        toOneRelations: (Students object) => [],
        toManyRelations: (Students object) => {},
        getId: (Students object) => object.id,
        setId: (Students object, int id) {
          object.id = id;
        },
        objectToFB: (Students object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final hobbieOffset = fbb.writeString(object.hobbie);
          final nacimientoOffset = fbb.writeString(object.nacimiento);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.edad);
          fbb.addOffset(3, hobbieOffset);
          fbb.addOffset(4, nacimientoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Students(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              edad: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              hobbie: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              nacimiento: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Students] entity fields to define ObjectBox queries.
class Students_ {
  /// see [Students.id]
  static final id = QueryIntegerProperty<Students>(_entities[0].properties[0]);

  /// see [Students.name]
  static final name = QueryStringProperty<Students>(_entities[0].properties[1]);

  /// see [Students.edad]
  static final edad =
      QueryIntegerProperty<Students>(_entities[0].properties[2]);

  /// see [Students.hobbie]
  static final hobbie =
      QueryStringProperty<Students>(_entities[0].properties[3]);

  /// see [Students.nacimiento]
  static final nacimiento =
      QueryStringProperty<Students>(_entities[0].properties[4]);
}
